[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.1"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Mead & Hunt","Eric Craft"]

# The title and description fields are primarily for displaying extension info in UI
title = "Mead & Hunt Delete Unused Materials"
description="Utility to delete unbound materials from the scene."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/ericcraft-mh/meadhunt-utility-materials-deleteunused"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["kit", "meadhunt","utility","materials","deleteunused"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import meadhunt.utility.materials.deleteunused".
[[python.module]]
name = "meadhunt.utility.materials.deleteunused"
